# coding: utf-8

# flake8: noqa
"""
    DASS Text Extractions Schema

    OpenAPI-style specification of the Text Extractions Schema   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: claytonm@arizona.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from schemas.model.te.one_of_te_text_extractions_events_items import OneOfTETextExtractionsEventsItems
from schemas.model.te.te_entity import TEEntity
from schemas.model.te.te_event import TEEvent
from schemas.model.te.te_event_bequeath import TEEventBequeath
from schemas.model.te.te_event_nomination import TEEventNomination
from schemas.model.te.te_object import TEObject
from schemas.model.te.te_text_extractions import TETextExtractions
