# coding: utf-8

# flake8: noqa
"""
    DASS Will Model Schema

    OpenAPI-style specification of the Will Model Schema   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: salena@arizona.edu, claytonm@arizona.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from schemas.model.wm.one_of_wms_expr_args_items import OneOfWMSExprArgsItems
from schemas.model.wm.one_of_wms_expr_fn import OneOfWMSExprFn
from schemas.model.wm.wm_asset import WMAsset
from schemas.model.wm.wm_conditional import WMConditional
from schemas.model.wm.wm_directive_bequeath import WMDirectiveBequeath
from schemas.model.wm.wm_directive_body import WMDirectiveBody
from schemas.model.wm.wm_directive_statement import WMDirectiveStatement
from schemas.model.wm.wm_enum_named_function import WMEnumNamedFunction
from schemas.model.wm.wm_literal_value import WMLiteralValue
from schemas.model.wm.wm_person import WMPerson
from schemas.model.wm.wm_predicate import WMPredicate
from schemas.model.wm.wms_expr import WMSExpr
from schemas.model.wm.wm_type_beneficiary import WMTypeBeneficiary
from schemas.model.wm.wm_variable_reference import WMVariableReference
from schemas.model.wm.wm_will_model import WMWillModel
