# coding: utf-8

"""
    DASS Text Extractions Schema

    OpenAPI-style specification of the Text Extractions Schema   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: claytonm@arizona.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TEEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'texts': 'list[str]',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'texts': 'texts',
        'type': 'type'
    }

    def __init__(self, id=None, texts=None, type=None):  # noqa: E501
        """TEEntity - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._texts = None
        self._type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if texts is not None:
            self.texts = texts
        if type is not None:
            self.type = type

    @property
    def id(self):
        """Gets the id of this TEEntity.  # noqa: E501

        A string representing the identifier of the entity, using Soundex convention. E.g., \"A630_1\" for the first intance of \"Arwood\"   # noqa: E501

        :return: The id of this TEEntity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TEEntity.

        A string representing the identifier of the entity, using Soundex convention. E.g., \"A630_1\" for the first intance of \"Arwood\"   # noqa: E501

        :param id: The id of this TEEntity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def texts(self):
        """Gets the texts of this TEEntity.  # noqa: E501

        Array of 1 or more strings representing the source text that is judged to refer to the entity   # noqa: E501

        :return: The texts of this TEEntity.  # noqa: E501
        :rtype: list[str]
        """
        return self._texts

    @texts.setter
    def texts(self, texts):
        """Sets the texts of this TEEntity.

        Array of 1 or more strings representing the source text that is judged to refer to the entity   # noqa: E501

        :param texts: The texts of this TEEntity.  # noqa: E501
        :type: list[str]
        """

        self._texts = texts

    @property
    def type(self):
        """Gets the type of this TEEntity.  # noqa: E501

        The DASS entity type   # noqa: E501

        :return: The type of this TEEntity.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TEEntity.

        The DASS entity type   # noqa: E501

        :param type: The type of this TEEntity.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TEEntity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TEEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
