# coding: utf-8

"""
    DASS Text Extractions Schema

    OpenAPI-style specification of the Text Extractions Schema   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: claytonm@arizona.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TEEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'testator_died': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'testator_died': 'TestatorDied'
    }

    def __init__(self, id=None, type=None, testator_died=None):  # noqa: E501
        """TEEvent - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._testator_died = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if testator_died is not None:
            self.testator_died = testator_died

    @property
    def id(self):
        """Gets the id of this TEEvent.  # noqa: E501

        A string representing the identifier of the event.   # noqa: E501

        :return: The id of this TEEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TEEvent.

        A string representing the identifier of the event.   # noqa: E501

        :param id: The id of this TEEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this TEEvent.  # noqa: E501

        The type of the event.  # noqa: E501

        :return: The type of this TEEvent.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TEEvent.

        The type of the event.  # noqa: E501

        :param type: The type of this TEEvent.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def testator_died(self):
        """Gets the testator_died of this TEEvent.  # noqa: E501

        Trigger label that was extracted from the NLP annotations  # noqa: E501

        :return: The testator_died of this TEEvent.  # noqa: E501
        :rtype: str
        """
        return self._testator_died

    @testator_died.setter
    def testator_died(self, testator_died):
        """Sets the testator_died of this TEEvent.

        Trigger label that was extracted from the NLP annotations  # noqa: E501

        :param testator_died: The testator_died of this TEEvent.  # noqa: E501
        :type: str
        """

        self._testator_died = testator_died

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TEEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TEEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
