
name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/dass-wills'
    strategy:
      matrix:
        os: [ubuntu-20.04]


    steps:
    - uses: actions/checkout@v2

    - name: Continuous Integration
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends apt-utils\
            git curl gcc build-essential \
            pkg-config openjdk-8-jdk antlr4 \
            python3 python3-dev python3-pip python3-venv \
            graphviz libgraphviz-dev doxygen
        python3 -m venv dass_wills_venv
        source dass_wills_venv/bin/activate
        pip install --upgrade setuptools
        pip install wheel
        pip install -r requirements.txt
        cd docs
        mkdir -p build
        make apidocs
        make html