name: AutoMATES documentation deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

    - name: Build docs with Sphinx
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install \
          git \
          curl \
          build-essential \
          gcc \
          pkg-config \
          python3 \
          python3-dev \
          python3-pip \
          python3-venv \
          doxygen
        python3 -m venv dass_wills_venv
        source dass_wills_venv/bin/activate
        pip install --upgrade setuptools
        pip install wheel
        pip install -r requirements.txt

        pushd docs > /dev/null
          mkdir -p build
          make apidocs
          make html
        popd > /dev/null
    - name: Deploy docs to ml4ai.github.io/dass-wills
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs/build/html